export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST'
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS'
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL'

export const EVENT_REQUEST = 'EVENT_REQUEST'
export const EVENT_SUCCESS = 'EVENT_SUCCESS'
export const EVENT_FAIL = 'EVENT_FAIL'

export const EVENT_RESERVE_REQUEST = 'EVENT_RESERVE_REQUEST'
export const EVENT_RESERVE_SUCCESS = 'EVENT_RESERVE_SUCCESS'
export const EVENT_RESERVE_FAIL = 'EVENT_RESERVE_FAIL'